(() => {
  const US_STATE_CODE_BY_NAME = Object.freeze({
    alabama: "AL",
    alaska: "AK",
    arizona: "AZ",
    arkansas: "AR",
    california: "CA",
    colorado: "CO",
    connecticut: "CT",
    delaware: "DE",
    "district of columbia": "DC",
    florida: "FL",
    georgia: "GA",
    hawaii: "HI",
    idaho: "ID",
    illinois: "IL",
    indiana: "IN",
    iowa: "IA",
    kansas: "KS",
    kentucky: "KY",
    louisiana: "LA",
    maine: "ME",
    maryland: "MD",
    massachusetts: "MA",
    michigan: "MI",
    minnesota: "MN",
    mississippi: "MS",
    missouri: "MO",
    montana: "MT",
    nebraska: "NE",
    nevada: "NV",
    "new hampshire": "NH",
    "new jersey": "NJ",
    "new mexico": "NM",
    "new york": "NY",
    "north carolina": "NC",
    "north dakota": "ND",
    ohio: "OH",
    oklahoma: "OK",
    oregon: "OR",
    pennsylvania: "PA",
    "rhode island": "RI",
    "south carolina": "SC",
    "south dakota": "SD",
    tennessee: "TN",
    texas: "TX",
    utah: "UT",
    vermont: "VT",
    virginia: "VA",
    washington: "WA",
    "west virginia": "WV",
    wisconsin: "WI",
    wyoming: "WY",
  });

  globalThis.ApplyTexPanelShared = Object.freeze({
    FLOW_STORAGE_KEY: "applicationFlows",
    LOW_CONFIDENCE_CONTEXT_MESSAGE: "Open the original job page once, then return here.",
    US_STATE_CODE_BY_NAME,
    US_STATE_CODES: new Set(Object.values(US_STATE_CODE_BY_NAME)),
    PANEL_SCRIPT_MODULES: Object.freeze([
      "panel-shared.js",
      "panel-scan.js",
      "panel-fill.js",
      "panel-workday.js",
      "panel.js",
    ]),
  });
})();
